<?php
/**
 * ImportersApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 11.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ImportersApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImportersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for analyzeImportMigration
     *
     * Analyze imported migration.
     *
     */
    public function testAnalyzeImportMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkImportMigrationResources
     *
     * Check if all resources from the imported migration could be created..
     *
     */
    public function testCheckImportMigrationResources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createImportMigration
     *
     * Create a new import migration..
     *
     */
    public function testCreateImportMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createImportServerSettings
     *
     * Create settings for the server import.
     *
     */
    public function testCreateImportServerSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteImportMigration
     *
     * Delete single migration.
     *
     */
    public function testDeleteImportMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteImportServerSettings
     *
     * Delete settings for the server import.
     *
     */
    public function testDeleteImportServerSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImportMigration
     *
     * Fetches single migration details.
     *
     */
    public function testGetImportMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImportMigrationData
     *
     * Get import migration information.
     *
     */
    public function testGetImportMigrationData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImportMigrationLog
     *
     * Get the log for an import migration.
     *
     */
    public function testGetImportMigrationLog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImportMigrations
     *
     * List all import migrations.
     *
     */
    public function testGetImportMigrations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImportServerDomainsCached
     *
     * Returns cached domains.
     *
     */
    public function testGetImportServerDomainsCached()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImportServerPullDomains
     *
     * Pull domains form the remote server..
     *
     */
    public function testGetImportServerPullDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImportServerSettings
     *
     * Get settings for the server import.
     *
     */
    public function testGetImportServerSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listImportServerSettings
     *
     * List all server import settings.
     *
     */
    public function testListImportServerSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scanImportMigrations
     *
     * Scan for manually uploaded cPanel backups..
     *
     */
    public function testScanImportMigrations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferCPanelUserAccount
     *
     * Transfer user account from remote cPanel server.
     *
     */
    public function testTransferCPanelUserAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateImportServerSettings
     *
     * Update settings for the server import.
     *
     */
    public function testUpdateImportServerSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadImportMigration
     *
     * Upload file for analyzing and processing..
     *
     */
    public function testUploadImportMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
